spring.profiles.active=dev

spring.application.name=news-aggregator
spring.application.base-path=${spring.application.name}/api/v1

# Client Configurations
client.g-news.api-version=api/v4
client.news-api.api-version=v2

# Client gs-client endpoints
client.gs-client.gs-client-base-url=${client.g-news.base-url}
client.gs-client.gs-client-search-path=/${client.g-news.api-version}/search
client.gs-client.gs-client-top-headlines-path=/${client.g-news.api-version}/top-headlines

# Client news-api endpoints
client.news-api.news-api-base-url=${client.news-api.base-url}
client.news-api.news-api-search-path=/${client.news-api.api-version}/everything
client.news-api.news-api-top-headlines-path=/${client.news-api.api-version}/top-headlines
client.news-api.news-api-sources-path=/${client.news-api.api-version}/sources

error.code.file.name=error-codes

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html







