spring.profiles.active=dev

spring.application.name=news-aggregator
spring.application.base-path=${spring.application.name}/api/v1

# Client Configurations
client.g-news.api-version=api/v4

client.gs-client.gs-client-search-path=${client.g-news.base-url}/${client.g-news.api-version}/search

error.code.file.name=error-codes






