server.port=8080

logging.level.com.example.new_aggregator=INFO

spring.datasource.url=jdbc:mysql://localhost:3306/newsDB?user=root
spring.datasource.username=root
spring.datasource.password=Shanmukha@5525
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# client configurations
client.g-news.base-url=https://gnews.io
client.g-news.api-key=f87e6d0fa711e7a57304f6cc564ed44f

client.news-api.base-url=https://newsapi.org
client.news-api.api-key=a485fa1f5a69408c9524d2dfb179b15a

#spring.security.user.name=admin
#spring.security.user.password=$2a$12$Vzh3xTPmpBjLYkfD/TTf8eiHb9.kdC7MgNwisHlZxSpK/u1WveJIO
#spring.security.user.roles=USER,ADMIN